### PR TITLE
Added temperature functionality. Settings in the editor now perdure b…

### PR DESCRIPTION
**Pull request by ivan-amaya**
…etween scenes.

### CODE REVIEW

**Comment by ReneX13** [comment]
Hey, I tried doing the merging and all that, but even git hub was like "Theres more than 3000 differences". So Im gonna get

the code I had cleaned up before and like merge the code manually. After we demo it, we go to the lab and create a new branch

and just keep working of of that one

________________________________

**Comment by ivan-amaya** [comment]
@ReneX13 Ok, yeah let's do that then!

**Comment by ReneX13** [comment]
Is your code working properly... we might have to use your for demoing lol

________________________________

**Comment by ivan-amaya** [comment]
@ReneX13 yeah, in fact I already have the latest version on the webpage, check it out. We can demo from there... or I also have the executable.

**Comment by ReneX13** [comment]
ok cool. You want to just merge the code in the lab after the meeting. We'll just need to add to the discrete counts, temp and cam controllers to the

clean code.

________________________________

**Pull request merged**
